### PR TITLE
Get max-eid from index if not present in db

### LINKED ISSUE #465: [Bug]: init max-ent-id from index if needed
### What version of Datahike are you using?

0.3.7-SNAPSHOT

### What version of Java are you using?

openjdk 11.0.11 2021-04-20

### What operating system are you using?

Ubuntu 20.04

### What database EDN configuration are you using?

- 

### Describe the bug

The max-ent-id is not recovered automatically from the index when an old Datahike instance is being used. 

### What is the expected behaviour?

We should have a fallback to recover the max-eid when it is not yet stored in the database, i.e. extract it from the index again with (db/init-max-eid eavt-key) in this case.

### How can the behaviour be reproduced?

-

### PR DESCRIPTION
**Pull request by MrEbbinghaus**
#### SUMMARY
This fixes #465 by getting the max-eid from the index if it is not present in the db record.

##### Bugfix
- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added
   - I am not sure how to add this. 
- [ ] ~~Architecture Decision Record added if design changes necessary~~
- [x] Formatting checked
- [x] `CHANGELOG.md` updated
   - The same as: "Persist max-eid"?

### CODE REVIEW

**Comment by kordano** [comment]
Thanks for the contribution @MrEbbinghaus, I could draft a test snippet to test the max-eid. As for the changelog I would write something like initialize max-eid.

**Review by kordano — COMMENTED** [review]
Thanks @MrEbbinghaus. For testing I'm creating a previous database that does not have the max-eid yet. I'll add the link to the database here once I have created it and made it available for testing.

**Comment by MrEbbinghaus** [comment]
Hey @kordano tested it locally with a database of mine (Unfortunately I can't publish it).

I was thinking about an automated test for this?

**Comment by MrEbbinghaus** [comment]
@kordano Hm.. Maybe the `:max-eid` should be ensured on connect? What do you think?

**Comment by jsmassa** [comment]
I also think it should be ensured on `-connect`. As far as I can see, in all other cases, the `max-eid` should already be present.

@kordano Did the underlying problem also show up in your compatibility tests? If yes, can they serve as a test for this issue? Otherwise it seems to me like it could get awkward testing this because it would require importing an old database.

**Comment by MrEbbinghaus** [comment]
@jsmassa Maybe this should be part of some kind of migration system? 

```clojure
(let [conf ...]
  (d.migration/migrate! conf)
  (d/connect conf))
```

I don't know if this is feasible, as it would require that any datahike version could connect to and migrate a database created with any previous version of datahike.

**Comment by jsmassa** [comment]
I'd say it could get a bit too complex for something integrated into datahike itself. What do you think, @kordano?

**Comment by MrEbbinghaus** [comment]
I will open a new MR for this issue, where I add the `max-eid` on connect.

**Pull request closed without merging**
