### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by TimoKramer**
Adapt api to match Datomic and test examples                                                                                                                               
                                                                                                                                                                           
- rename document heading because of layout                                                                                                                                
- rename some arguments for better compatibility                                                                                                                           
- change pull api to match Datomic                                                                                                                                         
- reformat docs for better layout                                                                                                                                          
- set no-doc for namespaces

### CODE REVIEW

**Comment by TimoKramer** [comment]
some more tests need to be implemented
[patch.txt](https://github.com/replikativ/datahike/files/5379592/patch.txt)

**Comment by TimoKramer** [comment]
functionality of `datoms` and `seek-datoms` need to be clarified with regards to #244 and #245

**Comment by TimoKramer** [comment]
should I rebase this branch on the clojure-cli-tools branch?

**Comment by TimoKramer** [comment]
Added the listen function into api namespace

**Comment by TimoKramer** [comment]
will add seek-datoms fix and squash

**Review by kordano — APPROVED** [review]

**Pull request merged**
