### PR TITLE
DynamoDB support.

### PR DESCRIPTION
**Pull request by csm**
Uses [konserve-ddb](https://github.com/csm/konserve-ddb).

* src/datahike/config.cljc (::backend): add :ddb.
  (do-uri->config): new multimethod, dispatch on backend.
  Provide :ddb implementation.
  (uri->config): defer to do-uri->config.
* src/datahike/store.cljc: add implementations for :ddb.
* project.clj: add konserve-ddb (as provided dependency).

### CODE REVIEW

**Comment by csm** [comment]
#89 may be more interesting than this.

**Comment by whilo** [comment]
In some sense you have parametrized `konserve` there so that it is able to cover the functionality in this branch as well, right?

**Comment by csm** [comment]
Yes, with `konserve-ddb-s3` just pass something that returns true for all keys to `consistent-key` and everything would be stored in DynamoDB. Though it would be odd to have to pass in a valid S3 bucket even though it's never used.

**Comment by kordano** [comment]
Since Datahike now uses external backend libraries over protocols I'll have to close this PR. I'll try to move it to a separate project.

**Pull request closed without merging**
