### PR TITLE
Fix: examples should use transact instead of (now undocumented) trans…

### PR DESCRIPTION
**Pull request by podgorniy**
#### SUMMARY
Update documentation examples with `transact` instead of `transact!`

##### Bugfix
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Architecture Decision Record added if design changes necessary
- [ ] Formatting checked
- [ ] `CHANGELOG.md` updated

##### Feature
- [ ] Implements an existing feature request. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Architecture Decision Record added 
- [ ] Formatting checked
- [ ] `CHANGELOG.md` updated

#### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by TimoKramer** [comment]
Thanks @podgorniy for improving the docs! While you're at it, could you maybe reformat it to use the :tx-data-format?

**Comment by podgorniy** [comment]
@TimoKramer I did not find any mentions of `:tx-data-format` in the datahike repository. Googling also did not give me information what you meant. If you tell me more what's that I'll take care of the `.md` documentation files.

**Comment by kordano** [comment]
Hi @podgorniy, we're trying to be compatible with the [transact](https://docs.datomic.com/client-api/datomic.client.api.html#var-transact) signature from Datomic which supports the transaction data as a hash-map with the attribute `:tx-data`. You can have a look at the resolution of the either sequence, map or vector in the [connector](https://github.com/replikativ/datahike/blob/main/src/datahike/connector.cljc#L75). Thanks for your help. :)

**Comment by podgorniy** [comment]
Updated `transact` calls in the in the docs `md` files. Also fixed some non-working examples (some place lacked `conn` arg, some place lacked namespace). Added better comments so developer is not surprised by exceptions (it was intended by the code, but not obvious from the comment).

**Review by TimoKramer — APPROVED** [review]

**Comment by TimoKramer** [comment]
Thanks a lot @podgorniy. I merged it.
We are always looking for people to improve and extend the docs. In case you want to continue on it, there is plenty to do and I am happy to open an issue for you with something you could work on. Apart from that you are always welcome to just pick one that suits you. 
Sorry for my incomplete advice that was not pointing you to the format of the arg-map format of the transact-fn.
Happy to chat with you on slack or in our GH-Discussions.

**Pull request merged**
