### PR TITLE
chore: remove incognito dependency

### PR DESCRIPTION
**Pull request by jsmassa**
#### SUMMARY
Removes incognito library which is not being used anymore.

### CODE REVIEW

**Review by whilo — DISMISSED** [review]

**Comment by whilo** [comment]
This also needs to be removed from konserve, if you want to get it out of the dependencies completely. It is still used by the hitchhiker-tree, though, right?

**Review by whilo — APPROVED** [review]
Thanks!

**Comment by TimoKramer** [comment]
@jsmassa merge?

**Comment by TimoKramer** [comment]
@whilo can you review again please? I removed clojurescript from deps and did some updates. (Unfortunately the latest releases of cheshire and persistent-sorted-set fails, so did not upgrade them)

**Comment by whilo** [comment]
We should port our native code from cheshire to jsonista and remove the dependency, I think. I will update persistent-sorted-set in my next PR after the server.

**Review by whilo — APPROVED** [review]
Looks good.

**Pull request merged**
