### PR TITLE
Restrict hht namespaces

### PR DESCRIPTION
**Pull request by jsmassa**
#### SUMMARY
- Restructures the index namespaces
- Introduces new multimethods for indexes
- Moves all hitchhiker-tree code to the appropriate namespace

##### Feature
- [ ] Implements an existing feature request. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Architecture Decision Record added 
- [x] Formatting checked
- [x] `CHANGELOG.md` updated

#### ADDITIONAL INFORMATION
Makes implementing new index types easier. Preparation work for adding the persistence layer for the persistent set.

### CODE REVIEW

**Comment by whilo** [comment]
As discussed, I think that `init-index` and `empty-index` should also receive a store or backend as an argument and not implicitly rely on the read-handlers.

https://github.com/replikativ/datahike/blob/ff893153bda317c6b95a253c87d05ea1c8cb2285/src/datahike/index/interface.cljc#L18

**Comment by whilo** [comment]
Other than that it looks good to me.

**Review by yflim — COMMENTED** [review]
Looks good to me

**Comment by jsmassa** [comment]
Commits will be merged with additions with PR #503

**Pull request closed without merging**
