### PR TITLE
WIP: Add type hints

### PR DESCRIPTION
**Pull request by jsmassa**
Version with all reflection warnings from datahike resolved and more type hints to resolve [unboxed math warnings](https://insideclojure.org/2014/12/15/warn-on-boxed/).

### CODE REVIEW

**Comment by jsmassa** [comment]
So far it looks like it makes the performance rather worse than better. My guess is added complexity due to type casts.
Still have to check the performance though in the bigger context.

**Comment by kordano** [comment]
Please convert to draft PR if it is not ready yet.

**Comment by jsmassa** [comment]
It is basically ready. We just should look at the benchmark results together to decide if we want to include it

**Comment by jsmassa** [comment]
Closing due to to unconvincing benchmark results.

**Pull request closed without merging**
