### PR TITLE
db.clj refactoring

### PR DESCRIPTION
**Pull request by jsmassa**

### CODE REVIEW

**Comment by jsmassa** [comment]
Closes #525

**Review by kordano — APPROVED** [review]
Looks good from top level, let's roll it out. I fear that all the other PRs will have a bad time rebaseing to this version but better now than later.

**Comment by kordano** [comment]
Could you check if that works with the latest rebase as well?

**Comment by whilo** [comment]
This looks good to me as well, but it is a bit difficult to see whether the functionality has changed somewhere or whether functions have just been pulled out to different namespaces. I think it is the latter and in this case everything should be fine. 

It is a bit annoying that I have to rebase my two open PRs for the GraalVM support and the global address space again after this, but hopefully it won't cost me more than a few hours. Ideally we should settle PRs affecting functionality before doing refactorings like this and plan this a bit ahead to avoid such rebases.

**Pull request merged**
