### PR TITLE
Use hash of datoms instead of EAVT index for calculating DB hash

### PR DESCRIPTION
**Pull request by purrgrammer**

### CODE REVIEW

**Comment by purrgrammer** [comment]
Should make #37 pass all the tests. /cc @kordano

**Comment by kordano** [comment]
Thanks for your contribution @purrgrammer , I'll review it in the evening.

**Comment by kordano** [comment]
Looks good, thanks again.

**Comment by whilo** [comment]
This fix requires to iterate over all datoms to create the hash, this means it is O(n) in the size of the database. It will probably be used in many internal functions of Clojure or even the JVM, e.g. HashMaps. The right way is to fix the hash calculation of the EAVT index object.

**Comment by whilo** [comment]
Ok, it is cached in this context, so probably it is fine. It is still curious that it is not behaving right for the EAVT index.

**Comment by whilo** [comment]
The problem is that equality for `defrecord` in the hitchhiker-tree implementation tracks mutable values that differ and are accounted by the default `.equals` and `.hashCode` implementations.

**Comment by whilo** [comment]
@purrgrammer @kordano The `O(n)` cost is definitely unnecessary and can make the whole system hang for arbitrary length of time in unintuitive situations where `.hashCode` is called internally. 

So the proper way to fix this, I think, is to calculate a rolling hash and store it within the root. Since the order of insertions does not matter it is enough to calculate the hash of each datom on insertion and add it to the current DB hash modulo `Long.MAX_VALUE` (or just accepting overflow). This will then work independent from index implementation. @purrgrammer Could you provide a patch for this?

**Comment by purrgrammer** [comment]
> So the proper way to fix this, I think, is to calculate a rolling hash and store it within the root. Since the order of insertions does not matter it is enough to calculate the hash of each datom on insertion and add it to the current DB hash modulo Long.MAX_VALUE (or just accepting overflow). This will then work independent from index implementation.

I agree, sounds good!

>  @purrgrammer Could you provide a patch for this?

Sure.

**Pull request merged**
