### PR TITLE
Fix premature termination of hitchhiker tree -slice

### PR DESCRIPTION
**Pull request by yflim**
#### SUMMARY
The current hitchhiker-tree -slice method terminates before all datoms meeting selection criteria are selected.

##### Bugfix
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Architecture Decision Record added if design changes necessary
- [ ] Formatting checked
- [ ] `CHANGELOG.md` updated

### CODE REVIEW

**Comment by jsmassa** [comment]
Does this address an issue that can be closed with this PR or does it solve a problem you found?

**Comment by jsmassa** [comment]
Why does it work with your fix and didn't work before?

**Comment by yflim** [comment]
> Does this address an issue that can be closed with this PR or does it solve a problem you found?
The latter

**Comment by yflim** [comment]
> Why does it work with your fix and didn't work before?
The tests I added fail without the fix—not all datoms that fall within the specified range are fetched.

**Comment by jsmassa** [comment]
But did you find out what the problem was?

**Comment by jsmassa** [comment]
Ah, I found out myself.

**Review by jsmassa — APPROVED** [review]
I am surprised that this problem wasn't found earlier. Thanks for fixing it!

**Pull request merged**
