### PR TITLE
Fixed a bug in the Datom's `entryAt` implementation

### PR DESCRIPTION
**Pull request by green-coder**
Added the missing `.` in a constructor call.

### CODE REVIEW

**Comment by green-coder** [comment]
It would be a good idea to add some tests, I can do that after work or you can also do it on your side:

`(select-keys (dd/datom 1 :foo "bar") [:e :a :v])`

**Review by whilo — APPROVED** [review]
Thank you! This looks good to me.

**Comment by whilo** [comment]
@green-coder Adding a test would definitely be very good.

**Comment by green-coder** [comment]
I added some tests.

**Comment by green-coder** [comment]
This PR is ready for reviews.

**Review by kordano — APPROVED** [review]

**Comment by green-coder** [comment]
@kordano I just noticed that the namespace for the test file is wrong.

**Comment by kordano** [comment]
Could you create a new PR with the fixed name?

**Comment by green-coder** [comment]
I can do that this weekend.

**Comment by TimoKramer** [comment]
I am fixing this together with the formatting. So no need to do that.

**Pull request merged**
