### PR TITLE
ADR build tooling

### PR DESCRIPTION
**Pull request by TimoKramer**

### CODE REVIEW

**Review by groundedSAGE — DISMISSED** [review]

**Comment by TimoKramer** [comment]
we will be talking about it in dev-meeting on 24th of september 2020

**Comment by TimoKramer** [comment]
@kordano can be merged if you are happy with it.

**Comment by TimoKramer** [comment]
@kordano Please add the following environment variables to the clojars-deploy context in circleci:
CLOJARS_USERNAME the username
CLOJARS_PASSWORD the token
Thanks!

**Comment by kordano** [comment]
env vars were added now.

**Review by kordano — APPROVED** [review]

**Pull request merged**
