### PR TITLE
ci: add native image builds for linux and macos

### PR DESCRIPTION
**Pull request by TimoKramer**

### CODE REVIEW

**Comment by TimoKramer** [comment]
unfortunately seeing an exception during test when running on macos:
```
Exception in thread "async-dispatch-309" java.lang.AssertionError: java.io.IOException: Bad file descriptor
	at java.base@22.0.2/sun.nio.ch.AsynchronousFileChannelImpl.addToFileLockTable(AsynchronousFileChannelImpl.java:174)
	at java.base@22.0.2/sun.nio.ch.SimpleAsynchronousFileChannelImpl.implLock(SimpleAsynchronousFileChannelImpl.java:187)
	at java.base@22.0.2/sun.nio.ch.AsynchronousFileChannelImpl.lock(AsynchronousFileChannelImpl.java:118)
	at java.base@22.0.2/java.nio.channels.AsynchronousFileChannel.lock(AsynchronousFileChannel.java:590)
	at konserve.filestore$fn__21763$fn__21770$state_machine__6430__auto____21775$fn__21777$fn__21779.invoke(filestore.clj:176)
	at konserve.filestore$fn__21763$fn__21770$state_machine__6430__auto____21775$fn__21777.invoke(filestore.clj:176)
	at konserve.filestore$fn__21763$fn__21770$state_machine__6430__auto____21775.invoke(filestore.clj:176)
	at clojure.core.async.impl.runtime$run_state_machine.invokeStatic(runtime.clj:62)
	at clojure.core.async.impl.runtime$run_state_machine_wrapped.invokeStatic(runtime.clj:64)
	at konserve.filestore$fn__21763$fn__21770.invoke(filestore.clj:176)

**Comment by whilo** [comment]
Maybe it cannot access a temporary store at a path that does not exit and is created somewhere. Or there is a problem with file locking. Can you instrument the code to print when it is being invoked and see on which part of the filesystem the exception comes from?

**Comment by whilo** [comment]
What I mean is printing the filename so we know which file had a bad file descriptor.

**Review by whilo — COMMENTED** [review]
I would be happy to merge this even if MacOS does not work right now and we fix the konserve issue in a follow up PR. @TimoKramer does that make sense?

**Comment by TimoKramer** [comment]
Hey, please merge but I can fix a broken pipeline during the week earliest.

**Comment by TimoKramer** [comment]
Will try to fix the conflict later today

**Review by whilo — APPROVED** [review]
Thank you for working on this!

**Pull request merged**
