### PR TITLE
Reintroduce updated migrate namespace and test

### PR DESCRIPTION
**Pull request by jsmassa**
Updated and added old migrate namespace

### CODE REVIEW

**Comment by markusalbertgraf** [comment]
Hi,
I put :tx/user data on many transactions to check who changed what record when.
I also use :tx/comment for e.g. schema upgrades.
`(not= (:a d) :db/txInstant)` leaves me with only half of that information.
Is it best practice to discard that on migration?
There are certainly scenarios where that makes sense though I would like to keep that if I just update the db-software or implementation.
If it discards :db/txInstant, does it make sense to keep the rest of the transaction-entities?
Will the db run ok with partial entities imported and if :db/id 536870913 is free but some above are taken?
Or could this perhaps be optional?

Thank you for your work!

**Comment by whilo** [comment]
This migration code here is to keep compatibility with the code from `0.1.*`, where we just exported the EAVT index. It is true that we should export all transaction data from now onwards, @kordano is working on that separately. Neither this nor tx data was properly recorded in ´0.1.*´. @kordano Can you open and track an issue about this?

**Comment by kordano** [comment]
I'll create an issue on that. It is also related to #96

**Comment by markusalbertgraf** [comment]
Thank you!!!

**Comment by efraimmgon** [comment]
I realize I am late to the party, but why do `export-db` and `import-db` write and read from a file, instead of just returning and accepting a `coll` of `datoms`?

Wouldn't this make them more flexible?

**Comment by kordano** [comment]
We could add that as an option.

**Pull request merged**
