### PR TITLE
Comparators

### PR DESCRIPTION
**Pull request by jsmassa**
Closes issue #328

### CODE REVIEW

**Comment by jsmassa** [comment]
Tests are still failing on this due to arity exceptions. I cannot figure out why, but it seems to have to do with the protocols.

**Comment by kordano** [comment]
Could you post the stacktrace?

**Comment by jsmassa** [comment]
I fixed it now. Apparently it is not possible to give an arbitrary number of arguments to a protocol function.

**Review by whilo — APPROVED** [review]
This looks good. The cljs version is incomplete (you provide implementations for `java.util.Date`, which does not exist in cljs), but we can fix this later also. Also, for the data implementation, is it faster compared to the default reduction because you add the type hints?

**Comment by whilo** [comment]
Wasn't the original goal to add a string comparator?

**Comment by jsmassa** [comment]
Yes, and so I did. But it was that general that it turned out to work with all types so far, so I made it the default. I only left the special implementations that were already there.

**Pull request merged**
