### PR TITLE
Benchmarks extension

### PR DESCRIPTION
**Pull request by jsmassa**
Adds 
- csv export
- queries
- comparison of benchmarks results 

Try csv export with
`TIMBRE_LEVEL=':fatal' clj -M:benchmark run -d mem-set -t test-bench -o csv > bench-res.tsv`

Try comparison with
`TIMBRE_LEVEL=':fatal' clj -M:benchmark compare bench-res.edn bench-res.edn`

### CODE REVIEW

**Comment by grischoun** [comment]
@jsmassa I get this error when I try to compare benchmarks:


```
{:clojure.main/message
 "Execution error (IllegalArgumentException) at benchmark.compare/compare-benchmarks (compare.clj:56).\nDon't know how to create ISeq from: clojure.lang.Symbol\n",
 :clojure.main/triage
 {:clojure.error/class java.lang.IllegalArgumentException,
  :clojure.error/line 56,
  :clojure.error/cause
  "Don't know how to create ISeq from: clojure.lang.Symbol",
  :clojure.error/symbol benchmark.compare/compare-benchmarks,
  :clojure.error/source "compare.clj",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type java.lang.IllegalArgumentException,
    :message "Don't know how to create ISeq from: clojure.lang.Symbol",
    :at [clojure.lang.RT seqFrom "RT.java" 557]}],
  :trace
  [[clojure.lang.RT seqFrom "RT.java" 557]
   [clojure.lang.RT seq "RT.java" 537]
   [clojure.core$seq__5402 invokeStatic "core.clj" 137]
   [clojure.core$map$fn__5866 invoke "core.clj" 2746]
   [clojure.lang.LazySeq sval "LazySeq.java" 42]
   [clojure.lang.LazySeq seq "LazySeq.java" 51]
   [clojure.lang.RT seq "RT.java" 535]
   [clojure.core$seq__5402 invokeStatic "core.clj" 137]
   [clojure.core$concat$fn__5493 invoke "core.clj" 725]
   [clojure.lang.LazySeq sval "LazySeq.java" 42]
   [clojure.lang.LazySeq seq "LazySeq.java" 51]
   [clojure.lang.RT seq "RT.java" 535]
   [clojure.core$seq__5402 invokeStatic "core.clj" 137]
   [clojure.core$map$fn__5866 invoke "core.clj" 2746]
   [clojure.lang.LazySeq sval "LazySeq.java" 42]
   [clojure.lang.LazySeq seq "LazySeq.java" 51]
   [clojure.lang.RT seq "RT.java" 535]
   [clojure.core$seq__5402 invokeStatic "core.clj" 137]
   [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 24]
   [clojure.core.protocols$fn__8146 invokeStatic "protocols.clj" 75]
   [clojure.core.protocols$fn__8146 invoke "protocols.clj" 75]
   [clojure.core.protocols$fn__8088$G__8083__8101
    invoke
    "protocols.clj"
    13]
   [clojure.core$reduce invokeStatic "core.clj" 6828]
   [clojure.core$group_by invokeStatic "core.clj" 7146]
   [clojure.core$group_by invoke "core.clj" 7146]
   [benchmark.compare$compare_benchmarks invokeStatic "compare.clj" 56]
   [benchmark.compare$compare_benchmarks invoke "compare.clj" 44]
   [benchmark.core$_main invokeStatic "core.clj" 71]
   [benchmark.core$_main doInvoke "core.clj" 47]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 665]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause "Don't know how to create ISeq from: clojure.lang.Symbol"}}

```

**Comment by jsmassa** [comment]
That happens because a timbre compile message is also redirected to a file. I don't know yet how to get rid of it, otherwise I'd just implement the direct saving to a file. It works when you delete that line in both files.

**Comment by jsmassa** [comment]
The target file name can now be given directly as an argument to the commandline tool, so to execute use something like
`TIMBRE_LEVEL=':fatal' clj -M:benchmark run -d mem-set -t test-bench -o edn bench.edn` or just
`clj -M:benchmark run -d mem-set -t test-bench -o edn bench.edn` if you want to see more of the log messages.

**Review by grischoun — APPROVED** [review]
Looks good!

**Pull request merged**
