### PR TITLE
202 fix historical db printer

### PR DESCRIPTION
**Pull request by kordano**

### CODE REVIEW

**Comment by kordano** [comment]
I have to adjust again. It seems that the pretty printer also has some issues.

**Comment by kordano** [comment]
Reading through https://stackoverflow.com/a/49455269 and I think I'll have to think about the printing a little bit more.

**Comment by TimoKramer** [comment]
I converted this one to a draft because I wasn't sure if this PR is now ready to review. Is it?

**Comment by kordano** [comment]
I'll create a separate issue for the `pprint` function. Should now be ready for review.

**Comment by kordano** [comment]
I merged the current development branch into this PR. Should be ready for review now.

**Review by TimoKramer — APPROVED** [review]

**Pull request merged**
